### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Dysnomia2005** [sainttx/Holograms-Placeholders#2]
Not sure what's going on server on 1.14.1

[15:09:42] [Server thread/ERROR]: [HologramsPlaceholders] Unhandled exception occured in onPacketSending(PacketEvent) for HologramsPlaceholders
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.4.0-b421]
        at com.sainttx.holograms.placeholders.HologramPacketAdapter.onPacketSending(HologramPacketAdapter.java:45) ~[HologramsPlaceholders-2.7-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-b421]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:207) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 177.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 30 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}],
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 30 more
[15:09:42] [Server thread/ERROR]: Parameters:
  net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@56130a12[
    a=177
    b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@6dccbd4d, net.minecraft.server.v1_14_R1.DataWatcher$Item@73a126de, net.minecraft.server.v1_14_R1.DataWatcher$Item@5a5e2185, net.minecraft.server.v1_14_R1.DataWatcher$Item@519fbb5, net.minecraft.server.v1_14_R1.DataWatcher$Item@d37188e, net.minecraft.server.v1_14_R1.DataWatcher$Item@77da4820, net.minecraft.server.v1_14_R1.DataWatcher$Item@5ca30d57, net.minecraft.server.v1_14_R1.DataWatcher$Item@162d8125, net.minecraft.server.v1_14_R1.DataWatcher$Item@23eb0806, net.minecraft.server.v1_14_R1.DataWatcher$Item@655cf13, net.minecraft.server.v1_14_R1.DataWatcher$Item@4258a33b, net.minecraft.server.v1_14_R1.DataWatcher$Item@388626fc, net.minecraft.server.v1_14_R1.DataWatcher$Item@43d6a2d2, net.minecraft.server.v1_14_R1.DataWatcher$Item@6bd3d0ec, net.minecraft.server.v1_14_R1.DataWatcher$Item@6c15e7d6, net.minecraft.server.v1_14_R1.DataWatcher$Item@652d8d6e, net.minecraft.server.v1_14_R1.DataWatcher$Item@131b732b, net.minecraft.server.v1_14_R1.DataWatcher$Item@66ba8514, net.minecraft.server.v1_14_R1.DataWatcher$Item@25d2f542]
  ]

[15:09:42] [Server thread/ERROR]: [HologramsPlaceholders] Unhandled exception occured in onPacketSending(PacketEvent) for HologramsPlaceholders
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.sainttx.holograms.placeholders.HologramPacketAdapter.onPacketSending(HologramPacketAdapter.java:45) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:244) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1117) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:981) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:673) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:748) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:873) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:435) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1086) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.WorldServer.addPlayer0(WorldServer.java:917) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.WorldServer.addPlayerJoin(WorldServer.java:893) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:211) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 64.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 41 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}],
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 41 more

**Comment by ghost** [comment]
Same problem on Paper Spigot 1.14.2

**Comment by pgmann** [comment]
Heads up that this is caused by https://github.com/dmulloy2/ProtocolLib/issues/663, if you're interested in implementing a workaround there's an NMS solution using this method: https://github.com/filoghost/HolographicDisplays/commit/ffb868093067a7f049ccbf6f075cad5ab0bb98a8

**Comment by wiidotmom** [comment]
Same error on PaperSpigot 1.14.4

**Comment by pgmann** [comment]
@iGalaxyYT try with the latest version of protocollib. This should be fixed by this commit: https://github.com/dmulloy2/ProtocolLib/commit/b1efed0c0cbb20f83fa12464e441485edcd001f2
